# Startup profiling (run: ZSHRC_PROFILE=1 exec zsh)
if [[ -n "$ZSHRC_PROFILE" ]]; then
  zmodload zsh/datetime
  typeset -g _zshrc_start=$EPOCHREALTIME
  _profile() { printf "  %-25s %6.0fms\n" "$1" $(( ($EPOCHREALTIME - _zshrc_start) * 1000 )); }
else
  _profile() {}
fi

# ------------------------------------------------------------------------------
# Sheldon plugin manager
# ------------------------------------------------------------------------------
eval "$(sheldon source)"
_profile "sheldon"

# ------------------------------------------------------------------------------
# Git aliases (only the ones you actually use)
# ------------------------------------------------------------------------------
alias ga='git add'
alias gc='git commit -v'
alias gco='git checkout'
alias gp='git push'
alias gpr='git pull --rebase'
alias grbc='git rebase --continue'
alias gs='git status'
alias gll='git log --graph --pretty=oneline --abbrev-commit'

# ------------------------------------------------------------------------------
# Directory navigation
# ------------------------------------------------------------------------------
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# ------------------------------------------------------------------------------
# Environment variables
# ------------------------------------------------------------------------------
export DOCKER_HOST="unix://$HOME/.colima/docker.sock"

# ------------------------------------------------------------------------------
# PATH
# ------------------------------------------------------------------------------
export PATH="$HOME/.local/bin:$PATH"

# ------------------------------------------------------------------------------
# Tool initializations
# ------------------------------------------------------------------------------
eval "$(starship init zsh)"
_profile "starship"

eval "$(fnm env --use-on-cd --shell zsh)"
_profile "fnm"

# ------------------------------------------------------------------------------
# History configuration
# ------------------------------------------------------------------------------
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt SHARE_HISTORY

# Key bindings for history substring search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# ------------------------------------------------------------------------------
# Completion
# ------------------------------------------------------------------------------
autoload -Uz compinit
compinit -C
_profile "compinit"

# ------------------------------------------------------------------------------
# Utils
# ------------------------------------------------------------------------------
DOTFILES_DIR="$(dirname "$(dirname "$(readlink -f ~/.zshrc)")")"
source "$DOTFILES_DIR/utils/aws.sh"

# ------------------------------------------------------------------------------
# Finish profiling
# ------------------------------------------------------------------------------
_profile "total"
[[ -n "$ZSHRC_PROFILE" ]] && echo ""
unfunction _profile 2>/dev/null
